<?php
/**
 * game_data.php — the board and the deck. CONTENT, not rules: the engine
 * reads this and never writes it, and tools/simulate.py parses it, so the
 * tuning always runs against exactly what the server plays.
 *
 * ONE TRACK, Nation (+, federal power) against States (-, states' rights),
 * from -5 to +5.
 *
 * THREE WAYS TO PLAY A CARD, so three numbers on it:
 *
 *   profit     money, the ONLY way to score. Play it for profit and nothing
 *              else happens.
 *   positive   favourable coverage: pushes the track this far (signed), and
 *              counts that much influence on the candidate you name.
 *   negative   hostile coverage: pushes the other way (signed) and HARDER
 *              than the card's favourable coverage, counts as influence the
 *              same way, and costs the Union `stability`. Hostile coverage
 *              is the strong, dangerous way to push: its price is disunion.
 *
 * `stability` is paid ONLY when a card is played negatively; each card
 * touches stability once at most. Profit cards have profit alone.
 *
 * BALANCE RULE: within every release batch the Nation push on offer equals
 * the States push on offer, counting both the positive and the negative
 * option of every card. tools/simulate.py asserts it; change a number here
 * and the batch must still balance, and on every card that has both the
 * hostile push must be the larger (tools/simulate.py asserts both).
 *
 * DATED RELEASE. A card enters the deck at the first campaign held in or
 * after its year. The opening deck is everything up to 1796.
 *
 * Every number is a first draft worth arguing with.
 *
 * NOTE ON QUOTING: apostrophes inside these single-quoted strings must be
 * escaped (\'). An unescaped one is a parse error that takes the site down.
 */

/** The seventeen races. Each has exactly one nation and one states candidate. */
function vg_elections() {
  return [
    ['space' => 1, 'year' => 1796, 'historical_winner' => 'nation',
     'note' => 'The first contested election. Adams carried New England and the commercial seaboard.',
     'nation' => ['key' => 'adams_1796', 'name' => 'John Adams', 'party' => 'Federalist',
       'note' => 'Atlantic commerce, a funded debt, and a strong executive.'],
     'states' => ['key' => 'jefferson_1796', 'name' => 'Thomas Jefferson', 'party' => 'Democratic-Republican',
       'note' => 'An agrarian republic, free trade, and a government of enumerated powers.'],
    ],
    ['space' => 2, 'year' => 1800, 'historical_winner' => 'states',
     'note' => 'The Revolution of 1800. A tie with Burr threw it to the House for thirty-six ballots.',
     'nation' => ['key' => 'adams_1800', 'name' => 'John Adams', 'party' => 'Federalist',
       'note' => 'Peace with France cost him his own party.'],
     'states' => ['key' => 'jefferson_1800', 'name' => 'Thomas Jefferson', 'party' => 'Democratic-Republican',
       'note' => 'Ran against the Alien and Sedition Acts and the standing army that paid for them.'],
    ],
    ['space' => 3, 'year' => 1804, 'historical_winner' => 'states',
     'note' => 'Barely a contest: Jefferson carried every state but Connecticut and Delaware, 162 to 14.',
     'nation' => ['key' => 'pinckney_1804', 'name' => 'Charles C. Pinckney', 'party' => 'Federalist',
       'note' => 'A Federalist party shrunk to New England, running against Louisiana.'],
     'states' => ['key' => 'jefferson_1804', 'name' => 'Thomas Jefferson', 'party' => 'Democratic-Republican',
       'note' => 'Lower taxes, a smaller debt, and a country doubled in size.'],
    ],
    ['space' => 4, 'year' => 1808, 'historical_winner' => 'states',
     'note' => 'Fought over the Embargo, which had wrecked New England shipping.',
     'nation' => ['key' => 'pinckney_1808', 'name' => 'Charles C. Pinckney', 'party' => 'Federalist',
       'note' => 'A South Carolina Federalist carrying a New England grievance.'],
     'states' => ['key' => 'madison_1808', 'name' => 'James Madison', 'party' => 'Democratic-Republican',
       'note' => 'Architect of commercial coercion as an alternative to war.'],
    ],
    ['space' => 5, 'year' => 1812, 'historical_winner' => 'states',
     'note' => 'A wartime election. Clinton ran as the peace candidate on Federalist votes.',
     'nation' => ['key' => 'clinton_1812', 'name' => 'DeWitt Clinton', 'party' => 'Federalist coalition',
       'note' => 'A Republican running on Federalist money to end the war.'],
     'states' => ['key' => 'madison_1812', 'name' => 'James Madison', 'party' => 'Democratic-Republican',
       'note' => 'War with Britain as the completion of independence.'],
    ],
    ['space' => 6, 'year' => 1816, 'historical_winner' => 'states',
     'note' => 'The last Federalist candidate. Monroe won 183 to 34.',
     'nation' => ['key' => 'king_1816', 'name' => 'Rufus King', 'party' => 'Federalist',
       'note' => 'A New York Federalist carrying the stain of Hartford.'],
     'states' => ['key' => 'monroe_1816', 'name' => 'James Monroe', 'party' => 'Democratic-Republican',
       'note' => 'A Virginian who now wanted a bank, a tariff and a navy.'],
    ],
    ['space' => 7, 'year' => 1820, 'historical_winner' => 'states',
     'note' => 'The Era of Good Feelings. Monroe ran unopposed; one elector voted for Adams instead.',
     'nation' => ['key' => 'jqadams_1820', 'name' => 'John Quincy Adams', 'party' => 'Democratic-Republican',
       'note' => 'Not a candidate at all: a single New Hampshire elector\'s protest vote.'],
     'states' => ['key' => 'monroe_1820', 'name' => 'James Monroe', 'party' => 'Democratic-Republican',
       'note' => 'Re-elected with every electoral vote but one.'],
    ],
    ['space' => 8, 'year' => 1824, 'historical_winner' => 'nation',
     'note' => 'Jackson led the popular and electoral vote; the House chose Adams. The Corrupt Bargain.',
     'nation' => ['key' => 'jqadams_1824', 'name' => 'John Quincy Adams', 'party' => 'Democratic-Republican',
       'note' => 'Roads, canals, a national university, and the American System.'],
     'states' => ['key' => 'jackson_1824', 'name' => 'Andrew Jackson', 'party' => 'Democratic-Republican',
       'note' => 'The military hero as the outsider against a Washington arrangement.'],
    ],
    ['space' => 9, 'year' => 1828, 'historical_winner' => 'states',
     'note' => 'The first mass-participation campaign, and the dirtiest so far.',
     'nation' => ['key' => 'jqadams_1828', 'name' => 'John Quincy Adams', 'party' => 'National Republican',
       'note' => 'Defended the Tariff of Abominations he had not written.'],
     'states' => ['key' => 'jackson_1828', 'name' => 'Andrew Jackson', 'party' => 'Democrat',
       'note' => 'Rotation in office and hostility to concentrated financial power.'],
    ],
    ['space' => 10, 'year' => 1832, 'historical_winner' => 'states',
     'note' => 'A referendum on the Bank of the United States, held as South Carolina moved to nullify.',
     'nation' => ['key' => 'clay_1832', 'name' => 'Henry Clay', 'party' => 'National Republican',
       'note' => 'Forced the Bank question early and lost on it.'],
     'states' => ['key' => 'jackson_1832', 'name' => 'Andrew Jackson', 'party' => 'Democrat',
       'note' => 'Killed the Bank, then threatened to hang nullifiers.'],
    ],
    ['space' => 11, 'year' => 1836, 'historical_winner' => 'states',
     'note' => 'The Whigs ran several regional candidates at once and still lost.',
     'nation' => ['key' => 'harrison_1836', 'name' => 'William Henry Harrison', 'party' => 'Whig',
       'note' => 'Tippecanoe, tried out as a national candidate for the first time.'],
     'states' => ['key' => 'vanburen_1836', 'name' => 'Martin Van Buren', 'party' => 'Democrat',
       'note' => 'The party manager who built the machine, inheriting it.'],
    ],
    ['space' => 12, 'year' => 1840, 'historical_winner' => 'nation',
     'note' => 'Log cabins and hard cider. The Panic of 1837 did the rest.',
     'nation' => ['key' => 'harrison_1840', 'name' => 'William Henry Harrison', 'party' => 'Whig',
       'note' => 'A campaign of image with almost no platform, and it worked.'],
     'states' => ['key' => 'vanburen_1840', 'name' => 'Martin Van Buren', 'party' => 'Democrat',
       'note' => 'Van Ruin, blamed for a depression he did not cause.'],
    ],
    ['space' => 13, 'year' => 1844, 'historical_winner' => 'states',
     'note' => 'Texas annexation. Clay equivocated and lost New York by five thousand votes.',
     'nation' => ['key' => 'clay_1844', 'name' => 'Henry Clay', 'party' => 'Whig',
       'note' => 'Tried to hold North and South together on annexation and satisfied neither.'],
     'states' => ['key' => 'polk_1844', 'name' => 'James K. Polk', 'party' => 'Democrat',
       'note' => 'The first dark horse: Texas, Oregon, and a lower tariff.'],
    ],
    ['space' => 14, 'year' => 1848, 'historical_winner' => 'nation',
     'note' => 'Free Soil took enough of New York to decide it.',
     'nation' => ['key' => 'taylor_1848', 'name' => 'Zachary Taylor', 'party' => 'Whig',
       'note' => 'A Louisiana slaveholder who turned out to be an unbending Unionist.'],
     'states' => ['key' => 'cass_1848', 'name' => 'Lewis Cass', 'party' => 'Democrat',
       'note' => 'Invented popular sovereignty as a way of not answering the question.'],
    ],
    ['space' => 15, 'year' => 1852, 'historical_winner' => 'states',
     'note' => 'The Whig party won four states and never contested another election.',
     'nation' => ['key' => 'scott_1852', 'name' => 'Winfield Scott', 'party' => 'Whig',
       'note' => 'A general the southern Whigs would not run on.'],
     'states' => ['key' => 'pierce_1852', 'name' => 'Franklin Pierce', 'party' => 'Democrat',
       'note' => 'A northern man of southern principles, nominated on the forty-ninth ballot.'],
    ],
    ['space' => 16, 'year' => 1856, 'historical_winner' => 'states',
     'note' => 'Bleeding Kansas. A party four years old came second.',
     'nation' => ['key' => 'fremont_1856', 'name' => 'John C. Fremont', 'party' => 'Republican',
       'note' => 'Free soil, free men, and no southern ballot access at all.'],
     'states' => ['key' => 'buchanan_1856', 'name' => 'James Buchanan', 'party' => 'Democrat',
       'note' => 'Chosen largely because he had been abroad during Kansas-Nebraska.'],
    ],
    ['space' => 17, 'year' => 1860, 'historical_winner' => 'nation',
     'note' => 'Actually a four-way race; the board reduces it to the two candidates who defined the question.',
     'nation' => ['key' => 'lincoln_1860', 'name' => 'Abraham Lincoln', 'party' => 'Republican',
       'note' => 'Not one southern state placed him on the ballot.'],
     'states' => ['key' => 'douglas_1860', 'name' => 'Stephen A. Douglas', 'party' => 'Democrat',
       'note' => 'Campaigned in the South against secession once he knew he had lost.'],
    ],
  ];
}

/**
 * The deck, in date order. positive/negative: + toward Nation, - toward States.
 */
function vg_cards() {
  return [
    'stamp_act' => ['name' => 'The Stamp Act', 'year' => 1765, 'kind' => 'event',
      'profit' => 3, 'positive' => -1, 'negative' => 3, 'stability' => 1,
      'flavor' => 'A tax on every sheet a printer used. The printers led the resistance, and never forgot who had tried to tax the press.'],
    'boston_massacre' => ['name' => 'The Boston Massacre', 'year' => 1770, 'kind' => 'event',
      'profit' => 4, 'positive' => -1, 'negative' => 3, 'stability' => 2,
      'flavor' => 'Five dead on King Street. Revere\'s engraving of it outsold anything true.'],
    'tea_party' => ['name' => 'The Boston Tea Party', 'year' => 1773, 'kind' => 'event',
      'profit' => 4, 'positive' => -1, 'negative' => 2, 'stability' => 2,
      'flavor' => 'Three shiploads of East India tea in the harbour, and a question about who governs a colony.'],
    'common_sense' => ['name' => 'Common Sense', 'year' => 1776, 'kind' => 'event',
      'profit' => 6, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'Paine\'s pamphlet ran through edition after edition in months. Kings, it turned out, were optional.'],
    'declaration' => ['name' => 'The Declaration of Independence', 'year' => 1776, 'kind' => 'event',
      'profit' => 5, 'positive' => -1, 'negative' => 2, 'stability' => 2,
      'flavor' => 'Printed overnight as a broadside and read aloud from courthouse steps. Everyone would claim it.'],
    'saratoga' => ['name' => 'Saratoga', 'year' => 1777, 'kind' => 'event',
      'profit' => 5, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'Burgoyne surrendered an army, and France decided the rebellion was worth backing.'],
    'valley_forge' => ['name' => 'Valley Forge', 'year' => 1777, 'kind' => 'event',
      'profit' => 2, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'A winter camp starved by a Congress that could ask the states for supplies but not require them.'],
    'articles_confederation' => ['name' => 'The Articles of Confederation', 'year' => 1781, 'kind' => 'event',
      'profit' => 2, 'positive' => -2, 'negative' => 3, 'stability' => 1,
      'flavor' => 'A league of friendship among sovereign states, with no power to tax and no one to enforce it.'],
    'newburgh' => ['name' => 'The Newburgh Conspiracy', 'year' => 1783, 'kind' => 'event',
      'profit' => 2, 'positive' => 1, 'negative' => -2, 'stability' => 2,
      'flavor' => 'Unpaid officers threatened Congress. Washington fumbled for his spectacles and talked them down.'],
    'treaty_of_paris' => ['name' => 'The Treaty of Paris', 'year' => 1783, 'kind' => 'event',
      'profit' => 6, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'Independence, fisheries and the land to the Mississippi. Peace sells as well as war.'],
    'pennsylvania_packet' => ['name' => 'The First American Daily', 'year' => 1784, 'kind' => 'profit',
      'profit' => 6, 'positive' => 0, 'negative' => 0, 'stability' => 0,
      'flavor' => 'The Pennsylvania Packet went daily. Advertisers discovered they could reach a city every morning.'],
    'shays_rebellion' => ['name' => 'Shays\' Rebellion', 'year' => 1786, 'kind' => 'event',
      'profit' => 3, 'positive' => 1, 'negative' => -3, 'stability' => 2,
      'flavor' => 'Farmers closed the courts in western Massachusetts, and the Confederation could do nothing about it.'],
    'antifederalist_papers' => ['name' => 'Brutus and the Federal Farmer', 'year' => 1787, 'kind' => 'event',
      'profit' => 3, 'positive' => -1, 'negative' => 3, 'stability' => 1,
      'flavor' => 'The case against ratification: a consolidated government would swallow the states and the liberties with them.'],
    'constitutional_convention' => ['name' => 'The Constitutional Convention', 'year' => 1787, 'kind' => 'event',
      'profit' => 3, 'positive' => 2, 'negative' => -3, 'stability' => 1,
      'flavor' => 'Delegates sent to amend the Articles locked the doors in Philadelphia and wrote a new government.'],
    'federalist_papers' => ['name' => 'The Federalist', 'year' => 1787, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -3, 'stability' => 1,
      'flavor' => 'Eighty-five essays by Publius in the New York papers, arguing for a government that could act.'],
    'northwest_ordinance' => ['name' => 'The Northwest Ordinance', 'year' => 1787, 'kind' => 'event',
      'profit' => 3, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'Congress would govern the western territories, and no slavery would cross the Ohio.'],
    'gazette_of_the_us' => ['name' => 'The Gazette of the United States', 'year' => 1789, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'Fenno\'s paper followed the government to New York and spoke for Hamilton\'s Treasury.'],
    'judiciary_act' => ['name' => 'The Judiciary Act', 'year' => 1789, 'kind' => 'event',
      'profit' => 2, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'A Supreme Court, circuit courts and district courts: the federal government acquired a reach.'],
    'assumption' => ['name' => 'The Assumption of State Debts', 'year' => 1790, 'kind' => 'event',
      'profit' => 4, 'positive' => 2, 'negative' => -3, 'stability' => 2,
      'flavor' => 'The nation took on the war debts of the states, and the speculators who held them grew rich.'],
    'residence_act' => ['name' => 'The Residence Act', 'year' => 1790, 'kind' => 'event',
      'profit' => 4, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'The capital would go to the Potomac, the price the South extracted for assumption.'],
    'bank_of_the_us' => ['name' => 'The Bank of the United States', 'year' => 1791, 'kind' => 'event',
      'profit' => 5, 'positive' => 2, 'negative' => -3, 'stability' => 1,
      'flavor' => 'Hamilton\'s bank, chartered under powers the Constitution never named. Jefferson called it unconstitutional.'],
    'bill_of_rights' => ['name' => 'The Bill of Rights', 'year' => 1791, 'kind' => 'event',
      'profit' => 1, 'positive' => -1, 'negative' => 3, 'stability' => 2,
      'flavor' => 'Ten amendments, the first of which said Congress shall make no law abridging the freedom of the press.'],
    'national_gazette' => ['name' => 'The National Gazette', 'year' => 1791, 'kind' => 'event',
      'profit' => 4, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'Freneau\'s opposition paper, subsidised by a clerkship in Jefferson\'s own State Department.'],
    'report_manufactures' => ['name' => 'The Report on Manufactures', 'year' => 1791, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'Hamilton on why a farming republic should build factories it does not yet want.'],
    'rights_of_man' => ['name' => 'The Rights of Man', 'year' => 1791, 'kind' => 'event',
      'profit' => 4, 'positive' => -1, 'negative' => 2, 'stability' => 2,
      'flavor' => 'Paine\'s defence of the French Revolution, printed in America with a note from the Secretary of State.'],
    'postal_act_1792' => ['name' => 'The Postal Act of 1792', 'year' => 1792, 'kind' => 'profit',
      'profit' => 8, 'positive' => 0, 'negative' => 0, 'stability' => 0,
      'flavor' => 'Newspapers carried anywhere in the Union for a cent or a cent and a half, and printers swapped papers postage-free. A national press became a business.'],
    'citizen_genet' => ['name' => 'Citizen Genet', 'year' => 1793, 'kind' => 'event',
      'profit' => 3, 'positive' => -1, 'negative' => 2, 'stability' => 2,
      'flavor' => 'The French minister appealed to the people over Washington\'s head, and embarrassed his friends.'],
    'democratic_societies' => ['name' => 'The Democratic-Republican Societies', 'year' => 1794, 'kind' => 'event',
      'profit' => 3, 'positive' => -1, 'negative' => 2, 'stability' => 2,
      'flavor' => 'Clubs of mechanics and farmers toasting France. Washington blamed them for the rebellion in the west.'],
    'whiskey_rebellion' => ['name' => 'The Whiskey Rebellion', 'year' => 1794, 'kind' => 'event',
      'profit' => 3, 'positive' => 1, 'negative' => -2, 'stability' => 2,
      'flavor' => 'Thirteen thousand militia marched on western Pennsylvania to collect a tax on whiskey.'],
    'jay_treaty' => ['name' => 'The Jay Treaty', 'year' => 1795, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -2, 'stability' => 2,
      'flavor' => 'Peace with Britain, bought with the carrying trade. Burned in effigy from Boston to Charleston.'],
    'alien_sedition' => ['name' => 'The Alien and Sedition Acts', 'year' => 1798, 'kind' => 'event',
      'profit' => 2, 'positive' => 2, 'negative' => -3, 'stability' => 2,
      'flavor' => 'Twenty-five arrests, and most of them printers. The press learned what it was worth.'],
    'kentucky_resolutions' => ['name' => 'The Kentucky and Virginia Resolutions', 'year' => 1798, 'kind' => 'event',
      'profit' => 2, 'positive' => -1, 'negative' => 3, 'stability' => 2,
      'flavor' => 'Jefferson and Madison, anonymously, arguing that a state might judge the compact for itself.'],
    'xyz_affair' => ['name' => 'The XYZ Affair', 'year' => 1798, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'Millions for defence, not one cent for tribute. The best copy the Federalists ever had.'],
    'louisiana_purchase' => ['name' => 'The Louisiana Purchase', 'year' => 1803, 'kind' => 'event',
      'profit' => 6, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'Fifteen million dollars, and a strict constructionist who could not find the clause.'],
    'marbury' => ['name' => 'Marbury v. Madison', 'year' => 1803, 'kind' => 'event',
      'profit' => 2, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'Marshall gave up a commission and took the power to void an act of Congress.'],
    'chesapeake_affair' => ['name' => 'The Chesapeake Affair', 'year' => 1807, 'kind' => 'event',
      'profit' => 4, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'A British broadside into an American frigate in American water. Impressment made personal.'],
    'embargo_act' => ['name' => 'The Embargo Act', 'year' => 1807, 'kind' => 'event',
      'profit' => 3, 'positive' => -1, 'negative' => 2, 'stability' => 2,
      'flavor' => 'Grass grew on the wharves of Salem. New England read it as a southern war on shipping.'],
    'burr_conspiracy' => ['name' => 'The Burr Conspiracy', 'year' => 1807, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -3, 'stability' => 2,
      'flavor' => 'A former Vice President tried for treason over a western empire. Jefferson wanted him hanged; Marshall let him walk.'],
    'niles_register' => ['name' => 'Niles\' Weekly Register', 'year' => 1811, 'kind' => 'profit',
      'profit' => 6, 'positive' => 0, 'negative' => 0, 'stability' => 0,
      'flavor' => 'A Baltimore weekly of documents, prices and speeches, read in every state and quoted by every rival.'],
    'tippecanoe' => ['name' => 'Tippecanoe', 'year' => 1811, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -3, 'stability' => 1,
      'flavor' => 'Harrison\'s battle on the Wabash. It would still be winning him votes thirty years later.'],
    'gerrymander' => ['name' => 'The Gerrymander', 'year' => 1812, 'kind' => 'event',
      'profit' => 4, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'A Massachusetts district drawn in the shape of a salamander, signed into law by Governor Gerry.'],
    'war_of_1812' => ['name' => 'Mr. Madison\'s War', 'year' => 1812, 'kind' => 'event',
      'profit' => 4, 'positive' => -2, 'negative' => 3, 'stability' => 2,
      'flavor' => 'The second war of independence, or a Virginian adventure at New England expense.'],
    'hartford_convention' => ['name' => 'The Hartford Convention', 'year' => 1814, 'kind' => 'event',
      'profit' => 2, 'positive' => -2, 'negative' => 3, 'stability' => 2,
      'flavor' => 'New England Federalists met in secret to discuss leaving, and destroyed their own party.'],
    'treaty_of_ghent' => ['name' => 'The Treaty of Ghent', 'year' => 1814, 'kind' => 'event',
      'profit' => 5, 'positive' => 1, 'negative' => 0, 'stability' => 0,
      'flavor' => 'Status quo ante bellum. Everyone claimed to have won.'],
    'second_bank' => ['name' => 'The Second Bank of the United States', 'year' => 1816, 'kind' => 'event',
      'profit' => 5, 'positive' => 2, 'negative' => -3, 'stability' => 1,
      'flavor' => 'A national currency, and a monster, depending on which paper you took.'],
    'tariff_of_1816' => ['name' => 'The Tariff of 1816', 'year' => 1816, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'The first protective tariff, passed by southerners who had learned what a blockade does.'],
    'panic_of_1819' => ['name' => 'The Panic of 1819', 'year' => 1819, 'kind' => 'event',
      'profit' => 5, 'positive' => -2, 'negative' => 3, 'stability' => 2,
      'flavor' => 'The Bank called in its loans and the west discovered what credit was.'],
    'missouri_compromise' => ['name' => 'The Missouri Compromise', 'year' => 1820, 'kind' => 'event',
      'profit' => 4, 'positive' => 2, 'negative' => -3, 'stability' => 2,
      'flavor' => 'A fire bell in the night, muffled for thirty years by a line at 36 degrees 30 minutes.'],
    'monroe_doctrine' => ['name' => 'The Monroe Doctrine', 'year' => 1823, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'A hemisphere closed to European colonisation, announced by a nation that could not enforce it.'],
    'crawford_radicals' => ['name' => 'The Crawford Radicals', 'year' => 1823, 'kind' => 'event',
      'profit' => 3, 'positive' => -1, 'negative' => 3, 'stability' => 2,
      'flavor' => 'The Old Republicans rallied behind Crawford and the caucus. A stroke left their man half-blind before the canvass began.'],
    'american_system' => ['name' => 'The American System', 'year' => 1824, 'kind' => 'event',
      'profit' => 5, 'positive' => 2, 'negative' => -3, 'stability' => 1,
      'flavor' => 'Clay wanted tariffs, a bank and roads, and to be remembered for all three.'],
    'erie_canal' => ['name' => 'The Erie Canal', 'year' => 1825, 'kind' => 'event',
      'profit' => 6, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'Three hundred and sixty-three miles, and the price of flour in New York fell by half.'],
    'lowell_mills' => ['name' => 'The Lowell Mills', 'year' => 1826, 'kind' => 'event',
      'profit' => 6, 'positive' => 1, 'negative' => 0, 'stability' => 0,
      'flavor' => 'Textile capital with a moral architecture attached, and a constituency for protection.'],
    'sc_exposition' => ['name' => 'The South Carolina Exposition', 'year' => 1828, 'kind' => 'event',
      'profit' => 2, 'positive' => -2, 'negative' => 3, 'stability' => 2,
      'flavor' => 'Calhoun, anonymously and while Vice President, on the right of a state to say no.'],
    'tariff_abominations' => ['name' => 'The Tariff of Abominations', 'year' => 1828, 'kind' => 'event',
      'profit' => 3, 'positive' => 2, 'negative' => -3, 'stability' => 3,
      'flavor' => 'Written to be so bad it would fail, and passed anyway.'],
    'cotton_boom' => ['name' => 'The Cotton Boom', 'year' => 1830, 'kind' => 'event',
      'profit' => 7, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'Two thirds of American exports, sold to Liverpool. Independence was never that simple.'],
    'webster_hayne' => ['name' => 'The Webster-Hayne Debate', 'year' => 1830, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -3, 'stability' => 1,
      'flavor' => 'Liberty and Union, now and forever, one and inseparable. It sold very well in print.'],
    'bank_war' => ['name' => 'The Bank War', 'year' => 1832, 'kind' => 'event',
      'profit' => 4, 'positive' => -2, 'negative' => 3, 'stability' => 2,
      'flavor' => 'The Bank tried to make itself the election. Jackson was delighted to oblige.'],
    'force_bill' => ['name' => 'The Force Bill', 'year' => 1833, 'kind' => 'event',
      'profit' => 2, 'positive' => 1, 'negative' => -3, 'stability' => 3,
      'flavor' => 'Authority to collect the tariff by arms, signed the same day as the compromise that made it moot.'],
    'penny_press' => ['name' => 'The Penny Press', 'year' => 1833, 'kind' => 'profit',
      'profit' => 6, 'positive' => 0, 'negative' => 0, 'stability' => 0,
      'flavor' => 'A cent a copy, sold in the street rather than by subscription. Your own trade, industrialised.'],
    'gag_rule' => ['name' => 'The Gag Rule', 'year' => 1836, 'kind' => 'event',
      'profit' => 2, 'positive' => -1, 'negative' => 2, 'stability' => 2,
      'flavor' => 'Antislavery petitions tabled unread, which turned the right of petition into the argument.'],
    'specie_circular' => ['name' => 'The Specie Circular', 'year' => 1836, 'kind' => 'event',
      'profit' => 4, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'Public land for gold and silver only. The paper economy discovered how thin it was.'],
    'panic_of_1837' => ['name' => 'The Panic of 1837', 'year' => 1837, 'kind' => 'event',
      'profit' => 5, 'positive' => -1, 'negative' => 3, 'stability' => 2,
      'flavor' => 'Six years of depression, and a president renamed Van Ruin for the duration.'],
    'amistad' => ['name' => 'The Amistad', 'year' => 1839, 'kind' => 'event',
      'profit' => 3, 'positive' => 2, 'negative' => -3, 'stability' => 2,
      'flavor' => 'Africans who seized a slave ship were tried in Connecticut. John Quincy Adams took their case to the Supreme Court.'],
    'log_cabin_campaign' => ['name' => 'Log Cabin and Hard Cider', 'year' => 1840, 'kind' => 'event',
      'profit' => 5, 'positive' => 2, 'negative' => -3, 'stability' => 1,
      'flavor' => 'The Whigs sold a Virginia planter\'s son as a frontiersman, and printed songbooks by the hundred thousand.'],
    'tyler_vetoes' => ['name' => 'His Accidency\'s Vetoes', 'year' => 1841, 'kind' => 'event',
      'profit' => 3, 'positive' => -2, 'negative' => 3, 'stability' => 1,
      'flavor' => 'Tyler vetoed the Whig bank twice. His cabinet resigned and his party expelled him.'],
    'dorr_rebellion' => ['name' => 'The Dorr Rebellion', 'year' => 1842, 'kind' => 'event',
      'profit' => 3, 'positive' => -1, 'negative' => 2, 'stability' => 2,
      'flavor' => 'Rhode Island briefly had two governors, over who was allowed to vote.'],
    'webster_ashburton' => ['name' => 'The Webster-Ashburton Treaty', 'year' => 1842, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -3, 'stability' => 1,
      'flavor' => 'The Maine border settled by negotiation, without the war the papers had been promising.'],
    'telegraph' => ['name' => 'The Magnetic Telegraph', 'year' => 1844, 'kind' => 'profit',
      'profit' => 7, 'positive' => 0, 'negative' => 0, 'stability' => 0,
      'flavor' => 'Morse\'s line from Washington to Baltimore. News now moved faster than the mail that carried the papers.'],
    'texas_annexation' => ['name' => 'The Annexation of Texas', 'year' => 1845, 'kind' => 'event',
      'profit' => 5, 'positive' => -2, 'negative' => 3, 'stability' => 2,
      'flavor' => 'Admitted by joint resolution because a treaty could not get two thirds.'],
    'associated_press' => ['name' => 'The Associated Press', 'year' => 1846, 'kind' => 'profit',
      'profit' => 6, 'positive' => 0, 'negative' => 0, 'stability' => 0,
      'flavor' => 'New York papers pooled the cost of news from the Mexican War, and sold it to everyone else.'],
    'mexican_war' => ['name' => 'The Mexican War', 'year' => 1846, 'kind' => 'event',
      'profit' => 5, 'positive' => -2, 'negative' => 3, 'stability' => 2,
      'flavor' => 'American blood shed on American soil, if you accepted where the soil began.'],
    'oregon_treaty' => ['name' => 'Fifty-four Forty', 'year' => 1846, 'kind' => 'event',
      'profit' => 4, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'Fifty-four forty or fight, settled quietly at forty-nine.'],
    'wilmot_proviso' => ['name' => 'The Wilmot Proviso', 'year' => 1846, 'kind' => 'event',
      'profit' => 2, 'positive' => 2, 'negative' => -3, 'stability' => 2,
      'flavor' => 'Neither slavery nor involuntary servitude in any territory taken from Mexico. It passed the House eight times.'],
    'free_soil' => ['name' => 'The Free Soil Party', 'year' => 1848, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -3, 'stability' => 2,
      'flavor' => 'Free soil, free speech, free labor and free men. Van Buren ran on it and handed New York to Taylor.'],
    'rotary_press' => ['name' => 'The Rotary Press', 'year' => 1847, 'kind' => 'profit',
      'profit' => 8, 'positive' => 0, 'negative' => 0, 'stability' => 0,
      'flavor' => 'Hoe\'s type-revolving press printed thousands of sheets an hour. Circulation was now limited by readers, not machines.'],
    'gold_rush' => ['name' => 'The Gold Rush', 'year' => 1849, 'kind' => 'event',
      'profit' => 8, 'positive' => -1, 'negative' => 0, 'stability' => 0,
      'flavor' => 'Ninety thousand people crossed a continent in a year, and California wanted in at once.'],
    'compromise_1850' => ['name' => 'The Compromise of 1850', 'year' => 1850, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -2, 'stability' => 2,
      'flavor' => 'Five bills passed separately because no majority existed for all five together.'],
    'fugitive_slave_act' => ['name' => 'The Fugitive Slave Act', 'year' => 1850, 'kind' => 'event',
      'profit' => 3, 'positive' => -1, 'negative' => 3, 'stability' => 3,
      'flavor' => 'Federal power used against the North on behalf of the South, and it radicalised both.'],
    'georgia_platform' => ['name' => 'The Georgia Platform', 'year' => 1850, 'kind' => 'event',
      'profit' => 3, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'Georgia would accept the Compromise, and named the conditions under which it would not.'],
    'nashville_convention' => ['name' => 'The Nashville Convention', 'year' => 1850, 'kind' => 'event',
      'profit' => 2, 'positive' => -1, 'negative' => 2, 'stability' => 2,
      'flavor' => 'Nine states met to consider what the South would do if the territories were closed.'],
    'cheap_postage' => ['name' => 'The Cheap Postage Act', 'year' => 1851, 'kind' => 'profit',
      'profit' => 6, 'positive' => 0, 'negative' => 0, 'stability' => 0,
      'flavor' => 'Congress cut newspaper postage again, and the country weekly reached its county for next to nothing.'],
    'uncle_toms_cabin' => ['name' => 'Uncle Tom\'s Cabin', 'year' => 1852, 'kind' => 'event',
      'profit' => 6, 'positive' => 1, 'negative' => -3, 'stability' => 2,
      'flavor' => 'Three hundred thousand copies in a year. The best-selling argument any of you ever printed.'],
    'transcontinental_railroad' => ['name' => 'The Pacific Railroad Surveys', 'year' => 1853, 'kind' => 'event',
      'profit' => 6, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'Every proposed route was an argument about which section would own the future.'],
    'gadsden_purchase' => ['name' => 'The Gadsden Purchase', 'year' => 1854, 'kind' => 'event',
      'profit' => 5, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'Ten million dollars of desert, bought for a southern railroad route.'],
    'kansas_nebraska' => ['name' => 'The Kansas-Nebraska Act', 'year' => 1854, 'kind' => 'event',
      'profit' => 3, 'positive' => -2, 'negative' => 3, 'stability' => 3,
      'flavor' => 'Douglas repealed the Missouri line to get his railroad, and detonated the party system.'],
    'ostend_manifesto' => ['name' => 'The Ostend Manifesto', 'year' => 1854, 'kind' => 'event',
      'profit' => 3, 'positive' => -2, 'negative' => 3, 'stability' => 2,
      'flavor' => 'Three ministers abroad proposed simply taking Cuba, and someone leaked it.'],
    'personal_liberty_laws' => ['name' => 'The Personal Liberty Laws', 'year' => 1855, 'kind' => 'event',
      'profit' => 3, 'positive' => 1, 'negative' => -3, 'stability' => 2,
      'flavor' => 'Northern states nullifying a federal statute, which the South noticed with interest.'],
    'bleeding_kansas' => ['name' => 'Bleeding Kansas', 'year' => 1856, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -3, 'stability' => 3,
      'flavor' => 'Two territorial governments, two constitutions, and a body count. Circulation soared.'],
    'filibusters' => ['name' => 'The Filibusters', 'year' => 1856, 'kind' => 'event',
      'profit' => 3, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'Walker took Nicaragua with fifty-eight men and reinstated slavery there.'],
    'sumner_caning' => ['name' => 'The Caning of Charles Sumner', 'year' => 1856, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -2, 'stability' => 3,
      'flavor' => 'Beaten unconscious on the Senate floor. The South sent Brooks replacement canes.'],
    'dred_scott' => ['name' => 'Dred Scott v. Sandford', 'year' => 1857, 'kind' => 'event',
      'profit' => 3, 'positive' => -2, 'negative' => 3, 'stability' => 3,
      'flavor' => 'No rights which the white man was bound to respect, and Congress powerless in the territories.'],
    'lecompton_constitution' => ['name' => 'The Lecompton Constitution', 'year' => 1857, 'kind' => 'event',
      'profit' => 3, 'positive' => -2, 'negative' => 3, 'stability' => 3,
      'flavor' => 'A proslavery constitution written by a minority, which split the Democratic party in two.'],
    'freeport_doctrine' => ['name' => 'The Freeport Doctrine', 'year' => 1858, 'kind' => 'event',
      'profit' => 4, 'positive' => -1, 'negative' => 2, 'stability' => 1,
      'flavor' => 'Douglas held that a territory could exclude slavery by simply declining to police it. It cost him the South.'],
    'lincoln_douglas' => ['name' => 'The Lincoln-Douglas Debates', 'year' => 1858, 'kind' => 'event',
      'profit' => 5, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'Seven towns, three hours each, printed verbatim in every paper in the country. Including yours.'],
    'ableman_v_booth' => ['name' => 'Ableman v. Booth', 'year' => 1859, 'kind' => 'event',
      'profit' => 2, 'positive' => 1, 'negative' => -2, 'stability' => 1,
      'flavor' => 'Taney told Wisconsin that no state court could overrule a federal one.'],
    'john_browns_raid' => ['name' => 'John Brown at Harpers Ferry', 'year' => 1859, 'kind' => 'event',
      'profit' => 4, 'positive' => 1, 'negative' => -2, 'stability' => 3,
      'flavor' => 'A martyr or a murderer, and no paper in the country could avoid choosing.'],
  ];
}

/** One race by space (1-based), or null. */
function vg_election_at($space) {
  foreach (vg_elections() as $e) {
    if ((int) $e['space'] === (int) $space) return $e;
  }
  return null;
}

/** One card by key, or null. */
function vg_card($key) {
  $cards = vg_cards();
  return isset($cards[$key]) ? $cards[$key] : null;
}

/**
 * Card keys released by a campaign: dated after $afterYear (exclusive; null
 * for the opening deck) and no later than $throughYear.
 */
function vg_cards_released($afterYear, $throughYear) {
  $out = [];
  foreach (vg_cards() as $key => $card) {
    $y = (int) $card['year'];
    if ($afterYear !== null && $y <= (int) $afterYear) continue;
    if ($y > (int) $throughYear) continue;
    $out[] = $key;
  }
  return $out;
}
