"""Write backend/cards_dc.php from the three content spreadsheets.

    py -X utf8 tools/export_cards_php.py          # write backend/cards_dc.php
    py -X utf8 tools/export_cards_php.py --check  # verify it matches the CSVs (needs php)

The spreadsheets in docs/ are the source of truth:
    docs/deck-dc.csv       every story, starter, Editorial and Scandal
    docs/elections-dc.csv  the 17 election cards
    docs/papers-dc.csv     the eight newspapers
The data is read through tools/simulate_dc.py's own loader, so the engine
and the simulator always play the same cards. Edit a CSV, rerun this, and
the next deploy carries it. Never edit backend/cards_dc.php by hand.
"""

import argparse
import json
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import simulate_dc as sim  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "backend", "cards_dc.php")

CARD_FIELDS = ["key", "name", "type", "theme", "cost", "vp", "gen", "themed", "campaign", "draw", "trash",
               "gain_upto", "chain", "per_same", "per_office", "attack", "defense", "retract",
               "ongoing_gen", "ongoing_draw", "others_bonus", "others_theme", "released", "year",
               "copies", "card_text", "flavor"]
ELECTION_FIELDS = ["space", "year", "era", "vp", "nation", "nation_theme", "nation_threshold",
                   "states", "states_theme", "states_threshold", "historical_winner",
                   "patron_gen", "patron_themed", "card_text"]
PAPER_FIELDS = ["key", "name", "dc_super_hero", "leans", "ability", "flavor"]
INTS = set(sim.INT) | {"space", "year", "vp", "nation_threshold", "states_threshold",
                       "patron_gen", "patron_themed", "released"}


def typed(record, fields):
    """The record as the engine should see it: ints as ints, blanks as null."""
    out = {}
    for f in fields:
        v = record.get(f)
        if f in INTS:
            out[f] = None if v in (None, "") else int(v)
        else:
            out[f] = None if v in (None, "") else str(v)
    return out


def content():
    cards = [typed(c, CARD_FIELDS) for c in sim.CARDS.values()]
    elections = [typed(e, ELECTION_FIELDS) for e in sim.ELECTIONS]
    papers = [typed(p, PAPER_FIELDS) for p in sim.PAPERS.values()]
    return cards, elections, papers


def php_value(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    return "'" + v.replace("\\", "\\\\").replace("'", "\\'") + "'"


def php_array(record, fields, indent):
    pad = " " * indent
    return "[" + ", ".join("'%s' => %s" % (f, php_value(record[f])) for f in fields) + "]"


def write():
    cards, elections, papers = content()
    lines = [
        "<?php",
        "/**",
        " * cards_dc.php -- GENERATED by tools/export_cards_php.py from",
        " * docs/deck-dc.csv, docs/elections-dc.csv and docs/papers-dc.csv.",
        " * DO NOT EDIT BY HAND: edit the spreadsheets and rerun the exporter.",
        " *",
        " * The DC-style Fourth Estate (VARIANT.md revision 4): stories, starters,",
        " * Editorial and Scandal; the 17 election cards (two thresholds each);",
        " * the eight newspapers.",
        " */",
        "",
        "/** Every card kind, keyed by card key. 'copies' is how many exist. */",
        "function dc_cards() {",
        "  static $cards = null;",
        "  if ($cards !== null) return $cards;",
        "  $cards = [",
    ]
    for c in cards:
        lines.append("    '%s' => %s," % (c["key"], php_array(c, CARD_FIELDS, 4)))
    lines += ["  ];", "  return $cards;", "}", "",
              "/** The 17 election cards in order, 1796 first. */",
              "function dc_elections() {",
              "  static $elections = null;",
              "  if ($elections !== null) return $elections;",
              "  $elections = ["]
    for e in elections:
        lines.append("    %s," % php_array(e, ELECTION_FIELDS, 4))
    lines += ["  ];", "  return $elections;", "}", "",
              "/** The eight newspapers (DC's Super Heroes), keyed by paper key. */",
              "function dc_papers() {",
              "  static $papers = null;",
              "  if ($papers !== null) return $papers;",
              "  $papers = ["]
    for p in papers:
        lines.append("    '%s' => %s," % (p["key"], php_array(p, PAPER_FIELDS, 4)))
    lines += ["  ];", "  return $papers;", "}", "",
              "/** One card kind by key ('scandal#3' and 'letter#0.2' resolve to their kind), or null. */",
              "function dc_card($key) {",
              "  $cards = dc_cards();",
              "  $kind = explode('#', (string) $key, 2)[0];",
              "  return $cards[$kind] ?? null;",
              "}", "",
              "/** The election card at index $i (0 = 1796), or null. */",
              "function dc_election($i) {",
              "  $e = dc_elections();",
              "  return $e[(int) $i] ?? null;",
              "}", ""]
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    print("wrote %s: %d card kinds, %d elections, %d papers"
          % (os.path.relpath(OUT, ROOT), len(cards), len(elections), len(papers)))


def check():
    """Load the PHP file with php and compare every field with the CSVs."""
    code = ("require %s; echo json_encode(['cards' => array_values(dc_cards()), "
            "'elections' => dc_elections(), 'papers' => array_values(dc_papers()), "
            "'lookup' => [dc_card('scandal#3')['key'], dc_card('letter#0.2')['key'], dc_election(16)['year']]]);"
            % php_value(OUT.replace("\\", "/")))
    try:
        raw = subprocess.run(["php", "-r", code], capture_output=True, text=True, encoding="utf-8", check=True).stdout
    except FileNotFoundError:
        sys.exit("php is not on PATH")
    except subprocess.CalledProcessError as e:
        sys.exit("php failed: %s" % (e.stderr or e.stdout))
    got = json.loads(raw)
    cards, elections, papers = content()
    problems = []
    for label, want, have in (("card", cards, got["cards"]), ("election", elections, got["elections"]),
                              ("paper", papers, got["papers"])):
        if len(want) != len(have):
            problems.append("%s count: csv %d, php %d" % (label, len(want), len(have)))
        for w, h in zip(want, have):
            for f, v in w.items():
                if h.get(f) != v:
                    problems.append("%s %s.%s: csv %r, php %r" % (label, w.get("key") or w.get("year"), f, v, h.get(f)))
    if got["lookup"] != ["scandal", "letter", 1860]:
        problems.append("lookup helpers: %r" % got["lookup"])
    if problems:
        print("MISMATCH (%d):" % len(problems))
        for p in problems[:30]:
            print("  " + p)
        sys.exit(1)
    fields = len(cards) * len(CARD_FIELDS) + len(elections) * len(ELECTION_FIELDS) + len(papers) * len(PAPER_FIELDS)
    print("backend/cards_dc.php matches the CSVs: %d cards, %d elections, %d papers, %d fields"
          % (len(cards), len(elections), len(papers), fields))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify backend/cards_dc.php against the CSVs")
    args = ap.parse_args()
    if args.check:
        check()
    else:
        write()


if __name__ == "__main__":
    main()
