"""Write backend/cards_2024.php from the 2024 game's content spreadsheets.

    py -X utf8 tools/export_cards_2024_php.py          # write backend/cards_2024.php
    py -X utf8 tools/export_cards_2024_php.py --check  # verify it matches the CSVs (needs php)

The spreadsheets in docs/ are the source of truth:
    docs/deck-2024.csv    every story, starter, Editorial and Scandal (tools/build_deck_2024.py)
    docs/states-2024.csv  the 51 contests (tools/build_states_2024.py)
The newspapers stay in docs/papers-dc.csv (backend/cards_dc.php). The data
is read through tools/simulate_2024.py's own loader, so the engine and the
simulator always play the same cards. Never edit backend/cards_2024.php by
hand.
"""

import argparse
import json
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import simulate_2024 as sim  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "backend", "cards_2024.php")

CARD_FIELDS = ["key", "name", "type", "kind", "lean", "cost", "vp", "stars", "gen", "themed", "campaign", "draw",
               "trash", "gain_upto", "chain", "per_same", "per_office", "attack", "defense", "retract",
               "ongoing_gen", "ongoing_draw", "others_bonus", "step", "year", "copies", "card_text", "flavor"]
STATE_FIELDS = ["key", "abbr", "state", "ev", "vp", "trump_pct", "harris_pct", "margin", "winner", "tier",
                "order", "deck"]
for _side in sim.SIDES:
    STATE_FIELDS += ["%s_%s" % (_side, f) for f in ("threshold", "gen", "party", "draw", "trash", "text")]
INTS = set(sim.INT) | {"stars", "step", "year", "ev", "vp", "order"} | {
    "%s_%s" % (s, f) for s in sim.SIDES for f in ("threshold", "gen", "party", "draw", "trash")}
FLOATS = {"trump_pct", "harris_pct", "margin"}


def typed(record, fields):
    """The record as the engine should see it: numbers as numbers, blanks as null."""
    out = {}
    for f in fields:
        v = record.get(f)
        if v in (None, ""):
            out[f] = None
        elif f in INTS:
            out[f] = int(v)
        elif f in FLOATS:
            out[f] = float(v)
        else:
            out[f] = str(v)
    return out


def content():
    cards = [typed(c, CARD_FIELDS) for c in sim.CARDS.values()]
    states = [typed(s, STATE_FIELDS) for s in sorted(sim.STATES.values(), key=lambda s: s["order"])]
    return cards, states


def php_value(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + v.replace("\\", "\\\\").replace("'", "\\'") + "'"


def php_array(record, fields):
    return "[" + ", ".join("'%s' => %s" % (f, php_value(record[f])) for f in fields) + "]"


def write():
    cards, states = content()
    lines = [
        "<?php",
        "/**",
        " * cards_2024.php -- GENERATED by tools/export_cards_2024_php.py from",
        " * docs/deck-2024.csv and docs/states-2024.csv.",
        " * DO NOT EDIT BY HAND: edit the spreadsheets and rerun the exporter.",
        " *",
        " * The 2024 game (VARIANT.md revision 5): stories, starters, Editorial and",
        " * Scandal; the 51 contests of the 2024 electoral college.",
        " */",
        "",
        "/** Every card kind, keyed by card key. 'copies' is how many exist. */",
        "function e24_cards() {",
        "  static $cards = null;",
        "  if ($cards !== null) return $cards;",
        "  $cards = [",
    ]
    for c in cards:
        lines.append("    '%s' => %s," % (c["key"], php_array(c, CARD_FIELDS)))
    lines += ["  ];", "  return $cards;", "}", "",
              "/** The 51 contests, keyed by state key, safest first; deck 'elections' = the big ten. */",
              "function e24_states() {",
              "  static $states = null;",
              "  if ($states !== null) return $states;",
              "  $states = ["]
    for s in states:
        lines.append("    '%s' => %s," % (s["key"], php_array(s, STATE_FIELDS)))
    lines += ["  ];", "  return $states;", "}", "",
              "function e24_card($key) {",
              "  $all = e24_cards();",
              "  return $all[$key] ?? null;",
              "}", "",
              "function e24_state($key) {",
              "  $all = e24_states();",
              "  return $all[$key] ?? null;",
              "}", ""]
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    print("wrote %s: %d cards, %d states" % (os.path.relpath(OUT, ROOT), len(cards), len(states)))


def check():
    """The PHP file's content, read back through php, against the CSVs."""
    cards, states = content()
    code = ("require '%s'; echo json_encode(['cards' => array_values(e24_cards()), "
            "'states' => array_values(e24_states())]);" % OUT.replace("\\", "/"))
    got = json.loads(subprocess.run(["php", "-r", code], capture_output=True, text=True, encoding="utf-8",
                                    check=True).stdout)
    norm = lambda rows: json.loads(json.dumps(rows))
    bad = []
    if norm(got["cards"]) != norm(cards):
        bad.append("cards")
    if norm(got["states"]) != norm(states):
        bad.append("states")
    if bad:
        print("backend/cards_2024.php is out of date (%s): run py -X utf8 tools/export_cards_2024_php.py"
              % ", ".join(bad))
        sys.exit(1)
    print("backend/cards_2024.php matches the spreadsheets (%d cards, %d states)." % (len(cards), len(states)))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    check() if args.check else write()
